name: Continuous Integration (core tests only)

on:
  push:
    branches:
      - master
      - stable-*
  pull_request:
    branches:
      - master
      - stable-*

jobs:
  build:
    uses: ./.github/workflows/ci-base.yml
    with:
      maven-opts: -Dskip-short-tc-ui-tests=true -Dskip-long-tc-ui-tests=true
